spring:
  application:
    name: hireath-eureka-server
  profiles: peer3
server:
  port: 8002
eureka:
  instance:
    hostname: peer3
  client:
    fetch-registry: false #如果为true，启动时报警.
    register-with-eureka: true #是否将自身注册
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/