---
spring:
  application:
    name: hireath-eureka-server
  profiles: peer1
server:
  port: 8000
eureka:
  instance:
    hostname: peer1
  client:
    fetch-registry: false #如果为true，启动时报警.
    register-with-eureka: true #是否将自身注册
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/