spring:
  application:
    name: hireath-eureka-server
  profiles: peer2
server:
  port: 8001
eureka:
  instance:
    hostname: peer2
  client:
    fetch-registry: false #如果为true，启动时报警.
    register-with-eureka: true #是否将自身注册
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/