server:
  port: 8888
spring:
  application:
    name: hireath-zuul
zuul:
  routes:
    demo:
      path: /test/**
      serviceId: spring-cloud-producer #http://ZUUL_HOST:ZUUL_PORT/微服务在Eureka上的serviceId/**会被转发到serviceId对应的微服务
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8000/eureka/